[package]
name = "MillerRabin_Prime_RNG"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"         # For random number generation
sys-info = "0.9"     # For system information (memory usage)
